// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dw.roo.catalog.domain;

import com.dw.roo.catalog.domain.Instructor;
import com.dw.roo.catalog.domain.InstructorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect InstructorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InstructorDataOnDemand: @Component;
    
    private Random InstructorDataOnDemand.rnd = new SecureRandom();
    
    private List<Instructor> InstructorDataOnDemand.data;
    
    public Instructor InstructorDataOnDemand.getNewTransientInstructor(int index) {
        Instructor obj = new Instructor();
        setEmail(obj, index);
        setFirstname(obj, index);
        setLastname(obj, index);
        return obj;
    }
    
    public void InstructorDataOnDemand.setEmail(Instructor obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void InstructorDataOnDemand.setFirstname(Instructor obj, int index) {
        String firstname = "firstname_" + index;
        obj.setFirstname(firstname);
    }
    
    public void InstructorDataOnDemand.setLastname(Instructor obj, int index) {
        String lastname = "lastname_" + index;
        obj.setLastname(lastname);
    }
    
    public Instructor InstructorDataOnDemand.getSpecificInstructor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Instructor obj = data.get(index);
        Long id = obj.getId();
        return Instructor.findInstructor(id);
    }
    
    public Instructor InstructorDataOnDemand.getRandomInstructor() {
        init();
        Instructor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Instructor.findInstructor(id);
    }
    
    public boolean InstructorDataOnDemand.modifyInstructor(Instructor obj) {
        return false;
    }
    
    public void InstructorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Instructor.findInstructorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Instructor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Instructor>();
        for (int i = 0; i < 10; i++) {
            Instructor obj = getNewTransientInstructor(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
