// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dw.roo.catalog.domain;

import com.dw.roo.catalog.domain.InstructorDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect InstructorDataOnDemand_Roo_Configurable {
    
    declare @type: InstructorDataOnDemand: @Configurable;
    
}
